GET http://localhost:3000/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxNSwidXNlcm5hbWUiOiJsYXdyZW5jZSBrYXR1dmEiLCJlbWFpbCI6ImxhcnJ5LmthdHV2YUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCRlb0NUTUwvNzFGQWVqc2YxZHdQaVFlb21CcU8zZlFSekZmNXBkeURRczFwYnFLSlk2anhQaSIsImlzX3ZlcmlmaWVkIjp0cnVlLCJpc19hY3RpdmUiOmZhbHNlLCJjcmVhdGVkQXQiOiIyMDIxLTAzLTE3VDE5OjQ1OjAxLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTAzLTE3VDIxOjQyOjI4LjAwMFoifSwiaWF0IjoxNjE2MDYyMDE4fQ.d_SmNulXjdFyQG0l-4Ldv9hxxwLiHFtapWw3Q_Jr7qY